label: 'Progenetix :: Template'
tagline: 'A Template for Creating Jekyll-Based Websites - Github or Standalone'
description: |
  The Jekyll-based website template, derived from the <a href="https://jekyll-themes.com/minimal/">"Minimal" theme</a> and used on a number of projects:
  - schemablocks.org
  - beacon-project.org
  - geagh-discovery.github.io
  - info.progenetix.org
  - info.baudisgroup.org
  - compbiozurich.org
  - ...
keywords: Jekyll, websites, Github
site_domain_name: progenetix.github.io/progenetix-site-template
url: 'https://progenetix.github.io/progenetix-site-template'

# The baseurl parameter is an empty string if the site is represented at the root
# of a domain:
# * For project domains on Github it corresponds to the project name.
# * If running the server locally for testing purposes, one has to provide an
#   empty string (--baseurl "") as command line parameter, if a different value
#   is being provided here.
baseurl: "/progenetix-site-template"

# the site_parent_link parameter is used e.g. for icon links.
site_parent_link: 'https://info.progenetix.org'
github_organisation: progenetix

# instructions for processing specific directories
include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".
# The "_posts" collection is created by default.
collections:
  doc:
    output: true
    permalink: /doc/:path/
  people:
    output: true
    permalink: /people/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout
nav_cat_blocks:     # comma-separated "label,type,label_visibility"
  general: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

# content of the different navigation blocks

# The `general` block is of type "categories" (defined above in `nav_cat_blocks`); i.e.
# the attributes there reflect Jekyll site `categories` as specified in the pages' YAML
# headers.
General:
  news: News
  people: Participants
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

# links added to the "General" categories block
general_outlinks:
  'Progenetix Resource': 'http://progenetix.org'

related_sites:
  'Baudisgroup at UZH': 'http://info.baudisgroup.org'
  'SchemaBlocks': 'http://schemablocks.org'

github_projects:
  'baudisgroup': 'http://github.com/baudisgroup/'
  'progenetix': 'http://github.com/progenetix/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'
  'ELIXIR Beacon': 'http://github.com/ga4gh-beacon/'

# The categories-date-sorted parameter determines the selection of a
# time sorted, year labeled listing template for those categories.
categories-date-sorted:
  - news
  - minutes
# As above, for tags:
tags-date-sorted:
  - press

# Only tags listed here will be considered for the tag cloud.
cloud_tags:
  - code
  - admins
  - contacts
  - contributors
  - developers
  - documentation
  - FAQ
  - Jekyll
  - Markdown
  - press
  - times
  - website

# additional Jekyll instructions
plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 3 # displayed sidebar links in current category
emptyArray: []          # dummy element for array instantiation
