label: 'Baudisgroup::Template'
tagline: 'A Template for Creating Jekyll-Based Websites'
description: |
  SchemaBlocks is a cross-workstream project of the Global Alliance for Genomics & Health
keywords: Jekyll, websites, Github
site_domain_name: template.baudisgroup.org
url: 'https://template.baudisgroup.org'
baseurl: ""
site_parent_link: 'https://info.baudisgroup.org'
github_organisation: baudisgroup

# instructions for processing specific directories

include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need 
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".
# The "_posts" collection is created by default

collections:
  people:
    output: true
    permalink: /people/:path/
  howto:
    output: true
    permalink: /howto/:path/
  minutes:
    output: true
    permalink: /minutes/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"
    
# navigation blocks can be used to separate different categories and add e.g. 
# external link block(s), in combination with a properly modified layout

nav_cat_blocks: # comma-separated "label,type,label_visibility"
  General: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

General:
  news: News
  people: Participants
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

categories_year_sorted:
  - news
  - minutes

related_sites: 
  'Baudisgroup at UZH': 'http://info.baudisgroup.org'
  'Progenetix': 'http://progenetix.org'
  'SchemaBlocks': 'http://schemablocks.org'

github_projects:
  'baudisgroup': 'http://github.com/baudisgroup/'
  'progenetix': 'http://github.com/progenetix/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'
  'ELIXIR Beacon': 'http://github.com/beacon-project/'
 
# tag_cloud items

cloud_tags:
  - code
  - admins
  - contacts
  - contributors
  - developers
  - press
  - times
  - Jekyll

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation

theme: jekyll-theme-minimal